In [44]:
import pandas as pd
import re

In [67]:
# Gene ids
gene_id_list = ['C5_00660C_A', 'C1_04770C_A', 'C1_02420C_A', 'CR_00850C_A', 'C5_03390C_A',
             'C6_00620W_A', 'C3_05920W_A', 'C3_05220W_A', 'C5_01840C_A', 'C1_08460C_A',
             'C3_04890W_A', 'C3_07860C_A', 'C6_03170C_A', 'C1_08590C_A', 'C3_02220W_A',
             'C1_00800C_A', 'C1_03780C_A', 'C3_06850W_A', 'CR_08780W_A', 'CR_08800W_A',
             'C1_00710C_A', "end"]

gene_names_list = ['ERG11', 'ERG3', 'FKS1', 'FKS2', 'FUR1', 'FCA1', 'MRR1', 'CDR1',
                   'TAC1', 'UPC2', 'CDR2', 'MRR2', 'MDR1', 'ERG1', 'CAP1', 'ERG2',
                   'HMG1', 'FCR1', 'ITS1', 'ITS2', 'TUB2']

In [45]:
test_file = 'test3.table'
control_file = 'control_albicans.table'

df_test = pd.read_csv(test_file, sep='\t')
df_control = pd.read_csv(control_file, sep='\t')

df_test = df_test.rename(columns={"NS.2209.003.UDP0161_i7---UDP0161_i5.fRS1_.GT": "sample1.GT", "NS.2209.003.UDP0163_i7---UDP0163_i5.fRS757_.GT": "sample2.GT", "NS.2209.003.UDP0167_i7---UDP0167_i5.A12_.GT" : "sample3.GT"})
df_control = df_control.rename(columns={"NS.2209.003.UDP0161_i7---UDP0161_i5.fRS1_.GT": "sample1.GT", "NS.2209.003.UDP0163_i7---UDP0163_i5.fRS757_.GT": "sample2.GT", "NS.2209.003.UDP0167_i7---UDP0167_i5.A12_.GT" : "sample3.GT"})

df_test.columns

Index(['CHROM', 'POS', 'REF', 'ALT', 'AC', 'AF', 'AN', 'sample1.GT',
       'sample2.GT', 'sample3.GT'],
      dtype='object')

In [46]:
# Only keep albicans in df_test

df_test_filtered = df_test[df_test['CHROM'] == 'Candidaalbicans']

df_test_filtered

,CHROM,POS,REF,ALT,AC,AF,AN,sample1.GT,sample2.GT,sample3.GT
1,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.
2,Candidaalbicans,148,T,C,2,0.500,4,T/C,T/C,./.
3,Candidaalbicans,182,CTA,C,1,0.250,4,CTA/CTA,CTA/C,./.
4,Candidaalbicans,186,G,GGT,1,0.250,4,G/G,G/GGT,./.
5,Candidaalbicans,478,G,A,2,0.500,4,G/A,G/A,./.
...,...,...,...,...,...,...,...,...,...,...
161,Candidaalbicans,51443,TGG,T,2,0.333,6,TGG/TGG,TGG/TGG,T/T
162,Candidaalbicans,51448,G,GAA,2,0.333,6,G/G,G/G,GAA/GAA
163,Candidaalbicans,51460,T,C,2,0.333,6,T/T,T/T,C/C
164,Candidaalbicans,51463,T,C,2,0.333,6,T/T,T/T,C/C
165,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T

In [47]:
# Exclude variants only called in sample 3. Sample 3 is broken.

def excludeSample(ref, sample1, sample2):
    alt1_1 = re.sub('\/[A-Z]*', '', sample1)
    alt2_1 = re.sub('\/[A-Z]*', '', sample2)
    alt1_2 = re.sub('[A-Z]*\/', '', sample1)
    alt2_2 = re.sub('[A-Z]*\/', '', sample2)
    if (ref == alt1_1) & (ref == alt2_1) & (ref == alt1_2) & (ref == alt2_2):
        return True
    else:
        return False

df_test_filtered['to_drop'] = df_test_filtered.apply(lambda row: excludeSample(row['REF'], row['sample1.GT'], row['sample2.GT']), axis=1)

df_test_filtered = df_test_filtered[df_test_filtered['to_drop'] == False]

df_test_filtered = df_test_filtered.drop(columns=['sample3.GT', 'to_drop'])

df_test_filtered

/tmp/ipykernel_5315/3183125931.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test_filtered['to_drop'] = df_test_filtered.apply(lambda row: excludeSample(row['REF'], row['sample1.GT'], row['sample2.GT']), axis=1)

               CHROM    POS  REF  ALT AC     AF  AN sample1.GT sample2.GT
1    Candidaalbicans    118    A    G  2  0.500   4        A/G        A/G
2    Candidaalbicans    148    T    C  2  0.500   4        T/C        T/C
3    Candidaalbicans    182  CTA    C  1  0.250   4    CTA/CTA      CTA/C
4    Candidaalbicans    186    G  GGT  1  0.250   4        G/G      G/GGT
5    Candidaalbicans    478    G    A  2  0.500   4        G/A        G/A
..               ...    ...  ...  ... ..    ...  ..        ...        ...
155  Candidaalbicans  46544    T    C  2  0.500   4        T/C        T/C
156  Candidaalbicans  46715    C    T  2  0.500   4        C/T        C/T
157  Candidaalbicans  46952    G    A  2  0.500   4        G/A        G/A
158  Candidaalbicans  47003    C    T  2  0.500   4        C/T        C/T
159  Candidaalbicans  47297    C    T  2  0.500   4        C/T        C/T

[156 rows x 9 columns]

In [48]:
df_control['to_drop'] = df_control.apply(lambda row: excludeSample(row['REF'], row['sample1.GT'], row['sample2.GT']), axis=1)

df_control_filtered = df_control[df_control['to_drop'] == False]

df_control_filtered = df_control_filtered.drop(columns=['sample3.GT', 'to_drop'])

df_control_filtered

,CHROM,POS,REF,ALT,AC,AF,AN,sample1.GT,sample2.GT
0,Ca22chr1A_C_albicans_SC5314,812,C,T,2,0.500,4,C/T,C/T
1,Ca22chr1A_C_albicans_SC5314,816,T,C,2,0.500,4,T/C,T/C
2,Ca22chr1A_C_albicans_SC5314,879,G,A,2,0.500,4,G/A,G/A
3,Ca22chr1A_C_albicans_SC5314,920,C,T,2,0.500,4,C/T,C/T
4,Ca22chr1A_C_albicans_SC5314,1621,A,T,3,0.750,4,T/T,A/T
...,...,...,...,...,...,...,...,...,...
20762,Ca22chr6A_C_albicans_SC5314,197027,C,T,4,1.00,4,T/T,T/T
20763,Ca22chr6A_C_albicans_SC5314,197029,G,A,4,1.00,4,A/A,A/A
20764,Ca22chr6A_C_albicans_SC5314,197031,C,T,4,1.00,4,T/T,T/T
20765,Ca22chr6A_C_albicans_SC5314,197045,T,C,4,1.00,4,C/C,C/C
20766,Ca22chr6A_C_albicans_SC5314,197174,G,A,4,1.00,4,A/A,A/A

In [65]:
### normalize control positions to synth genome
df_landmarks = pd.read_csv("../synth_genome/landmarks.csv")

df_landmarks

,Unnamed: 0,Species,Gene ID,Landmarks
0,0,Aspergillus fumigatus,"['AFUA_4G06890', 'AFUA_6G05140', 'AFUA_2G00320...","{'1': 0, '2': 4918979, '3': 9763451, '4': 1384..."
1,1,Candida albicans,"['C5_00660C_A', 'C1_04770C_A', 'C1_02420C_A', ...","{'Ca22chr1A_C_albicans_SC5314': 0, 'Ca22chr1B_..."
2,2,Candida auris,"['B9J08_001448', 'B9J08_003737', 'B9J08_000964...","{'PEKT02000001_C_auris_B8441': 0, 'PEKT0200000..."
3,3,Candida parapsilosis,"['CPAR2_303740', 'CPAR2_105550', 'CPAR2_106400...","{'Contig005504_C_parapsilosis_CDC317': 0, 'Con..."
4,4,Candida tropicalis,"['CTRG_05283', 'CTRG_04480', 'CTRG_04661', 'CT...","{'GG692418': 0, 'GG692395': 50304, 'GG692396':..."
5,5,Cryptococcus neoformans,"['CNA00300', 'CNN02320', 'CNE02100', 'CNA05950...","{'1': 0, '2': 2300533, '3': 3932840, '4': 6038..."
6,6,Nasakeomyces glabrata,"['CAGL0E04334g', 'CAGL0F01793g', 'CAGL0G01034g...","{'ChrA_C_glabrata_CBS138': 0, 'ChrB_C_glabrata..."
7,7,Pichia kudriavzevii,"['JL09_g2508', 'JL09_g3074', 'JL09_g1956', 'JL...","{'scaffold00001': 0, 'scaffold00002': 607893, ..."

In [66]:
# get absolute pos
def getAbsPos(chrom, pos, landmarks_dict):
    return int(int(landmarks_dict.get(chrom)) + pos)

df_control_filtered['abs pos'] = df_control_filtered.apply(lambda row: getAbsPos(row['CHROM'], row['POS'], eval(df_landmarks.iloc[1]['Landmarks'])), axis=1)

df_control_filtered

,CHROM,POS,REF,ALT,AC,AF,AN,sample1.GT,sample2.GT,abs pos
0,Ca22chr1A_C_albicans_SC5314,812,C,T,2,0.500,4,C/T,C/T,812
1,Ca22chr1A_C_albicans_SC5314,816,T,C,2,0.500,4,T/C,T/C,816
2,Ca22chr1A_C_albicans_SC5314,879,G,A,2,0.500,4,G/A,G/A,879
3,Ca22chr1A_C_albicans_SC5314,920,C,T,2,0.500,4,C/T,C/T,920
4,Ca22chr1A_C_albicans_SC5314,1621,A,T,3,0.750,4,T/T,A/T,1621
...,...,...,...,...,...,...,...,...,...,...
20762,Ca22chr6A_C_albicans_SC5314,197027,C,T,4,1.00,4,T/T,T/T,20224396
20763,Ca22chr6A_C_albicans_SC5314,197029,G,A,4,1.00,4,A/A,A/A,20224398
20764,Ca22chr6A_C_albicans_SC5314,197031,C,T,4,1.00,4,T/T,T/T,20224400
20765,Ca22chr6A_C_albicans_SC5314,197045,T,C,4,1.00,4,C/C,C/C,20224414
20766,Ca22chr6A_C_albicans_SC5314,197174,G,A,4,1.00,4,A/A,A/A,20224543

In [82]:
# get pos in gene if any...
# I think I dont need abs pos
#def getPosInGene(chrom, absPOS, landmarks_dict):
    
    # find gene coord in gff
    
    
rel_gene_coords_list = []

gff_file = '../synth_genome/gff_files/C_albicans_SC5314_version_A22-s07-m01-r195.gff'
    
with open(gff_file) as gff:
    gff_content = gff.read()
    
for geneID in gene_id_list:
    y = re.findall(f"^.*\t.*\tgene\t.*?{geneID}", gff_content, flags=re.MULTILINE)
    #print(y)
    coordinates = re.findall("[^\\t]+", y[0])
    
    landmark = coordinates[0]
    gene_begin = int(coordinates[3]) -1 #+ int(landmarks_dict.get(chrom))# Minus 1 to get to base 0 
    gene_end = int(coordinates[4]) #+ int(landmarks_dict.get(chrom)) # Here we do not substract because we want to include the last nucleotide.
    rel_gene_coords_list.append([gene_begin + eval(df_landmarks.iloc[1]['Landmarks']).get(landmark), gene_end + eval(df_landmarks.iloc[1]['Landmarks']).get(landmark)])
    #if (absPOS >= gene_begin) & (absPOS <= gene_end):
    #    return (absPOS - gene_begin, geneID)

#getPosInGene(df_control_filtered.iloc[34]['CHROM'], df_control_filtered.iloc[0]['abs pos'], eval(df_landmarks.iloc[1]['Landmarks']))
#print(len(df_albicans_genes.iloc[5]['dna seq']))
#df_control_filtered['POSinGene'], df_control_filtered['geneID'] = df_control_filtered.apply(lambda row: getPosInGene(row['CHROM'], row['abs pos'], eval(df_landmarks.iloc[1]['Landmarks'])), axis=1)
#df_control_filtered
rel_gene_coords_list

[[17793623, 17795210],
 [991621, 992782],
 [505968, 511662],
 [24225655, 24230578],
 [18411752, 18412409],
 [20139620, 20140143],
 [12169632, 12172959],
 [11986414, 11990920],
 [18061908, 18064854],
 [1858135, 1860274],
 [11888256, 11892756],
 [12618784, 12620917],
 [20693751, 20695446],
 [1880546, 1882037],
 [11319270, 11320770],
 [154632, 155286],
 [790363, 793585],
 [12408820, 12410374],
 [25926506, 25926645],
 [25926802, 25926953],
 [123868, 125597],
 [34524, 35679]]

In [91]:
string = ""
for i in rel_gene_coords_list:
    string += f"((df_control_filtered['abs pos'] >= {i[0]}) & (df_control_filtered['abs pos'] <= {i[1]})) | \n"
    
print(string)
#df_control_filtered = df_control_filtered[(df_control_filtered['abs pos'] >= 17793623) & (df_control_filtered['abs pos'] >= 17793623) |  
#                                           ]

((df_control_filtered['abs pos'] >= 17793623) & (df_control_filtered['abs pos'] <= 17795210)) |
((df_control_filtered['abs pos'] >= 991621) & (df_control_filtered['abs pos'] <= 992782)) |
((df_control_filtered['abs pos'] >= 505968) & (df_control_filtered['abs pos'] <= 511662)) |
((df_control_filtered['abs pos'] >= 24225655) & (df_control_filtered['abs pos'] <= 24230578)) |
((df_control_filtered['abs pos'] >= 18411752) & (df_control_filtered['abs pos'] <= 18412409)) |
((df_control_filtered['abs pos'] >= 20139620) & (df_control_filtered['abs pos'] <= 20140143)) |
((df_control_filtered['abs pos'] >= 12169632) & (df_control_filtered['abs pos'] <= 12172959)) |
((df_control_filtered['abs pos'] >= 11986414) & (df_control_filtered['abs pos'] <= 11990920)) |
((df_control_filtered['abs pos'] >= 18061908) & (df_control_filtered['abs pos'] <= 18064854)) |
((df_control_filtered['abs pos'] >= 1858135) & (df_control_filtered['abs pos'] <= 1860274)) |
((df_control_filtered['abs pos'] >= 11888256) & (df_control_filtered['abs pos'] <= 11892756)) |
((df_control_filtered['abs pos'] >= 12618784) & (df_control_filtered['abs pos'] <= 12620917)) |
((df_control_filtered['abs pos'] >= 20693751) & (df_control_filtered['abs pos'] <= 20695446)) |
((df_control_filtered['abs pos'] >= 1880546) & (df_control_filtered['abs pos'] <= 1882037)) |
((df_control_filtered['abs pos'] >= 11319270) & (df_control_filtered['abs pos'] <= 11320770)) |
((df_control_filtered['abs pos'] >= 154632) & (df_control_filtered['abs pos'] <= 155286)) |
((df_control_filtered['abs pos'] >= 790363) & (df_control_filtered['abs pos'] <= 793585)) |
((df_control_filtered['abs pos'] >= 12408820) & (df_control_filtered['abs pos'] <= 12410374)) |
((df_control_filtered['abs pos'] >= 25926506) & (df_control_filtered['abs pos'] <= 25926645)) |
((df_control_filtered['abs pos'] >= 25926802) & (df_control_filtered['abs pos'] <= 25926953)) |
((df_control_filtered['abs pos'] >= 123868) & (df_control_filtered['abs pos'] <= 125597)) |
((df_control_filtered['abs pos'] >= 34524) & (df_control_filtered['abs pos'] <= 35679)) |

In [94]:
df_control_filtered = df_control_filtered[((df_control_filtered['abs pos'] >= 17793623) & (df_control_filtered['abs pos'] <= 17795210)) | 
((df_control_filtered['abs pos'] >= 991621) & (df_control_filtered['abs pos'] <= 992782)) | 
((df_control_filtered['abs pos'] >= 505968) & (df_control_filtered['abs pos'] <= 511662)) | 
((df_control_filtered['abs pos'] >= 24225655) & (df_control_filtered['abs pos'] <= 24230578)) | 
((df_control_filtered['abs pos'] >= 18411752) & (df_control_filtered['abs pos'] <= 18412409)) | 
((df_control_filtered['abs pos'] >= 20139620) & (df_control_filtered['abs pos'] <= 20140143)) | 
((df_control_filtered['abs pos'] >= 12169632) & (df_control_filtered['abs pos'] <= 12172959)) | 
((df_control_filtered['abs pos'] >= 11986414) & (df_control_filtered['abs pos'] <= 11990920)) | 
((df_control_filtered['abs pos'] >= 18061908) & (df_control_filtered['abs pos'] <= 18064854)) | 
((df_control_filtered['abs pos'] >= 1858135) & (df_control_filtered['abs pos'] <= 1860274)) | 
((df_control_filtered['abs pos'] >= 11888256) & (df_control_filtered['abs pos'] <= 11892756)) | 
((df_control_filtered['abs pos'] >= 12618784) & (df_control_filtered['abs pos'] <= 12620917)) | 
((df_control_filtered['abs pos'] >= 20693751) & (df_control_filtered['abs pos'] <= 20695446)) | 
((df_control_filtered['abs pos'] >= 1880546) & (df_control_filtered['abs pos'] <= 1882037)) | 
((df_control_filtered['abs pos'] >= 11319270) & (df_control_filtered['abs pos'] <= 11320770)) | 
((df_control_filtered['abs pos'] >= 154632) & (df_control_filtered['abs pos'] <= 155286)) | 
((df_control_filtered['abs pos'] >= 790363) & (df_control_filtered['abs pos'] <= 793585)) | 
((df_control_filtered['abs pos'] >= 12408820) & (df_control_filtered['abs pos'] <= 12410374)) | 
((df_control_filtered['abs pos'] >= 25926506) & (df_control_filtered['abs pos'] <= 25926645)) | 
((df_control_filtered['abs pos'] >= 25926802) & (df_control_filtered['abs pos'] <= 25926953)) | 
((df_control_filtered['abs pos'] >= 123868) & (df_control_filtered['abs pos'] <= 125597))]
 
df_control_filtered

,CHROM,POS,REF,ALT,AC,AF,AN,sample1.GT,sample2.GT,abs pos
13017,Ca22chr3A_C_albicans_SC5314,1148705,A,T,4,1.00,4,T/T,T/T,11989075
18100,Ca22chr5A_C_albicans_SC5314,148296,CTA,C,2,0.500,4,CTA/CTA,C/C,17793805
18101,Ca22chr5A_C_albicans_SC5314,148300,G,GGT,2,0.500,4,G/G,GGT/GGT,17793809

In [ ]:
df_control_filtered.to_csv('checkpoint.csv')

In [4]:
# Merge on POS, REF and ALT

df_merged = df_test_filtered.merge(df_control_filtered, how='left', on=['POS', 'REF', 'ALT'], suffixes=('_test', '_control'))

# df_merged = df_merged[(df_merged['sample1.GT'] != './.' & df_merged['sample2.GT'] != './.')]
#df_merged = df_merged.loc[(df_merged['sample1.GT'] != './.') & (df_merged['sample2.GT'] != './.')]
df_merged #[0:15]

,CHROM_test,POS_test,REF,ALT,AC_test,AF_test,AN_test,sample1.GT,sample2.GT,sample3.GT_test,CHROM_control,POS_control,AC_control,AF_control,AN_control,sample3.GT_control
0,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4031.0,2,0.500,4.0,./.
1,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4042.0,2,0.500,4.0,./.
2,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4044.0,2,0.500,4.0,./.
3,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,6656.0,2,0.500,4.0,./.
4,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,8174.0,2,0.500,4.0,./.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87277,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,348856.0,2,0.333,6.0,T/T
87278,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946773.0,2,0.333,6.0,T/T
87279,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946782.0,2,0.333,6.0,T/T
87280,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946812.0,2,0.333,6.0,T/T
87281,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946943.0,2,0.333,6.0,T/T

In [5]:
# Get gene spans from synthetic genome only albicans ?

synth_gen = '../synth_genome/v4_synthetic_genome.fa'

with open(synth_gen) as genome:
    genome_content = genome.read()

# Removes first line puts a space
#dna = re.sub(">.*", "", genome_content)
genome_string = re.sub("\n", "", genome_content)
albicans_only = re.findall(r">Candidaalbicans\w*", genome_string, flags=re.MULTILINE)[0]

print(len(albicans_only))
print(albicans_only[0:100])

52547
>CandidaalbicansTTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGTTCAGTAGGTAAAACCACCATTGAACTATAATCAGGGTC

In [6]:
# remove header
albicans_only_sequences = re.sub(">Candidaalbicans", "", albicans_only)

print(albicans_only_sequences[0:100])

TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGTTCAGTAGGTAAAACCACCATTGAACTATAATCAGGGTCAGGCACTTTATAACCA

In [8]:
pattern = re.compile("[^N]*N*")
matches = pattern.finditer(albicans_only_sequences)

span_list = []
match_list = []

for i, match in enumerate(matches):
    gene = gene_id_list[i]
    span_list.append(match.span())
    #print(f'span {gene} : ', match.span())
    match_list.append(match.group())
    #print(f'match {gene} : ', match.group())

df_albicans_genes = pd.DataFrame()
df_albicans_genes['Gene ID'] = gene_id_list
df_albicans_genes['Gene name'] = gene_names_list
df_albicans_genes['synth genome positions'] = span_list
df_albicans_genes['match seq'] = match_list

df_albicans_genes

,Gene ID,synth genome positions,match seq
0,C5_00660C_A,"(0, 1887)",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
1,C1_04770C_A,"(1887, 3348)",TCATTGTTCAACATATTCTCTATCGTCAACTTTACCTTCAACTTCT...
2,C1_02420C_A,"(3348, 9342)",TTAAACTCTGAATGGATTTGTAGAATAAGGGGTGGTAGTTCCAGTA...
3,CR_00850C_A,"(9342, 14565)",CTAGTAATGCTTAATTTCTAATTTTTTCTTTAATCCTTTCAGATTT...
4,C5_03390C_A,"(14565, 15522)",TTAAATACAGTAATATCTATCACCGAAATCACCTAGACCTGGAACA...
5,C6_00620W_A,"(15522, 16345)",ATGACGTTTGACGACAAAAAAGGTTTACAAGTTGCTCTTGATCAAG...
6,C3_05920W_A,"(16345, 19972)",ATGTCAATTGCCACCACCCCTATAGAAACACCTAAAAGTCCTAAAA...
7,C3_05220W_A,"(19972, 24778)",ATGTCAGATTCTAAGATGTCGTCGCAAGATGAATCTAAATTAGAAA...
8,C5_01840C_A,"(24778, 28024)",TTAAATCCCCAAATTATTGTCAAAGAAAAAATTGGGTAAATTATTA...
9,C1_08460C_A,"(28024, 30463)",CTATTTCATATTCATAAACCCATTATCACCTTGCATTAAGTCTAAA...
10,C3_04890W_A,"(30463, 35263)",ATGAGTACTGCAAACACGTCTTTGTCGCAACAGCTAGACGAAAAGC...
11,C3_07860C_A,"(35263, 37696)",TTACGAGATTTTGAGGAAATCCCAATAATCCCAGTCCCAGTTTGAC...
12,C6_03170C_A,"(37696, 39691)",CTAATTAGCATACTTAGATCTTGCTCTCAACTTTGGTCCGTTCAAG...
13,C1_08590C_A,"(39691, 41482)",CTATCTTACAATCTCGTTCCATAAATATGGAGTAAAGATTACAATT...
14,C3_02220W_A,"(41482, 43282)",ATGACAGATATTAAAAGAAATTTTTCAGATATTGCCTCACCAGCAA...
15,C1_00800C_A,"(43282, 44236)",TTAGAATTTCCCAATTAATAAATTCTTGATCATATCTTTACCAGTG...
16,C1_03780C_A,"(44236, 47758)",CTAAGATTTAATACATGTTACTGAACCTTCTTCAAGACGTTTCAAA...
17,C3_06850W_A,"(47758, 49612)",ATGTCTGACGATCATTCAATCCATTCTCATACACAGGGACTCCACC...
18,CR_08780W_A,"(49612, 50051)",CTGATTTGCTTAATTGCACCACATGTGTTTTTCTTTGAAACAAACT...
19,CR_08800W_A,"(50051, 50502)",CTCCCTCAAACCGCTGGGTTTGGTGTTGAGCAATACGACTTGGGTT...
20,C1_00710C_A,"(50502, 52531)",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
21,end,"(52531, 52531)",

In [9]:
from Bio.Seq import Seq

In [10]:
def extract_exon_sequences(dna_sequence, exon_positions):
    gene_length = len(dna_sequence)
    exon_ranges = re.findall(r'(\d+)\.\.(\d+)', exon_positions)
    exon_sequences = []
    ## ignore this if all exon start at position 1
    # Calculate the adjustment value based on the start of the first exon
    if int(exon_ranges[-1][1]) > gene_length:
        first_start = int(exon_ranges[0][0])
        adjustment_value = first_start -1
    else:
        adjustment_value = 0
    for start, end in exon_ranges:
        start, end = int(start), int(end)
        adjusted_start = start - adjustment_value
        adjusted_end = end - adjustment_value
        exon_sequence = dna_sequence[adjusted_start -1:adjusted_end-1]
        exon_sequences.append(exon_sequence)
    return ''.join(exon_sequences)

In [11]:
def convert_position(exon_positions, position):
    exon_ranges = re.findall(r'(\d+)\.\.(\d+)', exon_positions)
    introns = []
    # Add an intron before the first exon
    first_exon_start = int(exon_ranges[0][0])
    if first_exon_start > 1:
        introns.append((1, first_exon_start - 1))
    # Iterate through consecutive exons to infer introns
    for i in range(1, len(exon_ranges)):
        previous_exon_end = int(exon_ranges[i - 1][1])
        current_exon_start = int(exon_ranges[i][0])
        # Infer intron between consecutive exons
        intron_start = previous_exon_end + 1
        intron_end = current_exon_start - 1
        # Add inferred intron to the list
        introns.append((intron_start, intron_end))
    adjusted_position = position
    for intron_start, intron_end in introns:
        if intron_end <= adjusted_position:
            # Adjust for intron
            adjusted_position -= (intron_end - intron_start + 1)
    protein_position = (adjusted_position - 1) // 3 + 1
    return protein_position

In [12]:
gene_seq_list = []

for match in match_list:
    gene_seq = re.sub("N", "", match)
    gene_seq_list.append(gene_seq)

df_albicans_genes['dna seq'] = gene_seq_list

df_albicans_genes

,Gene ID,synth genome positions,match seq,dna seq
0,C5_00660C_A,"(0, 1887)",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
1,C1_04770C_A,"(1887, 3348)",TCATTGTTCAACATATTCTCTATCGTCAACTTTACCTTCAACTTCT...,TCATTGTTCAACATATTCTCTATCGTCAACTTTACCTTCAACTTCT...
2,C1_02420C_A,"(3348, 9342)",TTAAACTCTGAATGGATTTGTAGAATAAGGGGTGGTAGTTCCAGTA...,TTAAACTCTGAATGGATTTGTAGAATAAGGGGTGGTAGTTCCAGTA...
3,CR_00850C_A,"(9342, 14565)",CTAGTAATGCTTAATTTCTAATTTTTTCTTTAATCCTTTCAGATTT...,CTAGTAATGCTTAATTTCTAATTTTTTCTTTAATCCTTTCAGATTT...
4,C5_03390C_A,"(14565, 15522)",TTAAATACAGTAATATCTATCACCGAAATCACCTAGACCTGGAACA...,TTAAATACAGTAATATCTATCACCGAAATCACCTAGACCTGGAACA...
5,C6_00620W_A,"(15522, 16345)",ATGACGTTTGACGACAAAAAAGGTTTACAAGTTGCTCTTGATCAAG...,ATGACGTTTGACGACAAAAAAGGTTTACAAGTTGCTCTTGATCAAG...
6,C3_05920W_A,"(16345, 19972)",ATGTCAATTGCCACCACCCCTATAGAAACACCTAAAAGTCCTAAAA...,ATGTCAATTGCCACCACCCCTATAGAAACACCTAAAAGTCCTAAAA...
7,C3_05220W_A,"(19972, 24778)",ATGTCAGATTCTAAGATGTCGTCGCAAGATGAATCTAAATTAGAAA...,ATGTCAGATTCTAAGATGTCGTCGCAAGATGAATCTAAATTAGAAA...
8,C5_01840C_A,"(24778, 28024)",TTAAATCCCCAAATTATTGTCAAAGAAAAAATTGGGTAAATTATTA...,TTAAATCCCCAAATTATTGTCAAAGAAAAAATTGGGTAAATTATTA...
9,C1_08460C_A,"(28024, 30463)",CTATTTCATATTCATAAACCCATTATCACCTTGCATTAAGTCTAAA...,CTATTTCATATTCATAAACCCATTATCACCTTGCATTAAGTCTAAA...
10,C3_04890W_A,"(30463, 35263)",ATGAGTACTGCAAACACGTCTTTGTCGCAACAGCTAGACGAAAAGC...,ATGAGTACTGCAAACACGTCTTTGTCGCAACAGCTAGACGAAAAGC...
11,C3_07860C_A,"(35263, 37696)",TTACGAGATTTTGAGGAAATCCCAATAATCCCAGTCCCAGTTTGAC...,TTACGAGATTTTGAGGAAATCCCAATAATCCCAGTCCCAGTTTGAC...
12,C6_03170C_A,"(37696, 39691)",CTAATTAGCATACTTAGATCTTGCTCTCAACTTTGGTCCGTTCAAG...,CTAATTAGCATACTTAGATCTTGCTCTCAACTTTGGTCCGTTCAAG...
13,C1_08590C_A,"(39691, 41482)",CTATCTTACAATCTCGTTCCATAAATATGGAGTAAAGATTACAATT...,CTATCTTACAATCTCGTTCCATAAATATGGAGTAAAGATTACAATT...
14,C3_02220W_A,"(41482, 43282)",ATGACAGATATTAAAAGAAATTTTTCAGATATTGCCTCACCAGCAA...,ATGACAGATATTAAAAGAAATTTTTCAGATATTGCCTCACCAGCAA...
15,C1_00800C_A,"(43282, 44236)",TTAGAATTTCCCAATTAATAAATTCTTGATCATATCTTTACCAGTG...,TTAGAATTTCCCAATTAATAAATTCTTGATCATATCTTTACCAGTG...
16,C1_03780C_A,"(44236, 47758)",CTAAGATTTAATACATGTTACTGAACCTTCTTCAAGACGTTTCAAA...,CTAAGATTTAATACATGTTACTGAACCTTCTTCAAGACGTTTCAAA...
17,C3_06850W_A,"(47758, 49612)",ATGTCTGACGATCATTCAATCCATTCTCATACACAGGGACTCCACC...,ATGTCTGACGATCATTCAATCCATTCTCATACACAGGGACTCCACC...
18,CR_08780W_A,"(49612, 50051)",CTGATTTGCTTAATTGCACCACATGTGTTTTTCTTTGAAACAAACT...,CTGATTTGCTTAATTGCACCACATGTGTTTTTCTTTGAAACAAACT...
19,CR_08800W_A,"(50051, 50502)",CTCCCTCAAACCGCTGGGTTTGGTGTTGAGCAATACGACTTGGGTT...,CTCCCTCAAACCGCTGGGTTTGGTGTTGAGCAATACGACTTGGGTT...
20,C1_00710C_A,"(50502, 52531)",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
21,end,"(52531, 52531)",,

In [13]:
### get exons

def getExons(geneID):
    
    gff_file = '../synth_genome/gff_files/C_albicans_SC5314_version_A22-s07-m01-r195.gff'
    
    with open(gff_file) as gff:
        gff_content = gff.read()
    
    # gene range
    y = re.findall(f"^.*\t.*\tgene\t.*?{geneID}", gff_content, flags=re.MULTILINE)
    coordinates = re.findall("[^\\t]+", y[0])
    #print(coordinates)
    gene_begin = int(coordinates[3]) -1 # Minus 1 to get to base 0 
    gene_end = int(coordinates[4]) # Here we do not substract because we want to include the last nucleotide.
    gene_range = gene_end - gene_begin
    #print(gene_range)
    
    # exons ranges
    w = re.findall(f"^.*\t.*\texon\t.*?{geneID}", gff_content, flags=re.MULTILINE)
    exon_relCoord_list = []
    for index, j in enumerate(w):
        exon_coord = re.findall("[^\\t]+", w[index])
        exon_begin = int(exon_coord[3]) - 1 - gene_begin
        exon_end = int(exon_coord[4]) - gene_begin
        exon_relCoord_list.append((exon_begin, exon_end))
    return exon_relCoord_list

#testing
#getExons(df_albicans_genes.iloc[5]['Gene ID'])
#print(len(df_albicans_genes.iloc[5]['dna seq']))

df_albicans_genes['exon coords'] = df_albicans_genes.apply(lambda row: getExons(row['Gene ID']), axis=1)

df_albicans_genes

,Gene ID,synth genome positions,match seq,dna seq,exon coords
0,C5_00660C_A,"(0, 1887)",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]"
1,C1_04770C_A,"(1887, 3348)",TCATTGTTCAACATATTCTCTATCGTCAACTTTACCTTCAACTTCT...,TCATTGTTCAACATATTCTCTATCGTCAACTTTACCTTCAACTTCT...,"[(0, 1161)]"
2,C1_02420C_A,"(3348, 9342)",TTAAACTCTGAATGGATTTGTAGAATAAGGGGTGGTAGTTCCAGTA...,TTAAACTCTGAATGGATTTGTAGAATAAGGGGTGGTAGTTCCAGTA...,"[(0, 5694)]"
3,CR_00850C_A,"(9342, 14565)",CTAGTAATGCTTAATTTCTAATTTTTTCTTTAATCCTTTCAGATTT...,CTAGTAATGCTTAATTTCTAATTTTTTCTTTAATCCTTTCAGATTT...,"[(0, 4923)]"
4,C5_03390C_A,"(14565, 15522)",TTAAATACAGTAATATCTATCACCGAAATCACCTAGACCTGGAACA...,TTAAATACAGTAATATCTATCACCGAAATCACCTAGACCTGGAACA...,"[(0, 657)]"
5,C6_00620W_A,"(15522, 16345)",ATGACGTTTGACGACAAAAAAGGTTTACAAGTTGCTCTTGATCAAG...,ATGACGTTTGACGACAAAAAAGGTTTACAAGTTGCTCTTGATCAAG...,"[(0, 55), (125, 523)]"
6,C3_05920W_A,"(16345, 19972)",ATGTCAATTGCCACCACCCCTATAGAAACACCTAAAAGTCCTAAAA...,ATGTCAATTGCCACCACCCCTATAGAAACACCTAAAAGTCCTAAAA...,"[(0, 3327)]"
7,C3_05220W_A,"(19972, 24778)",ATGTCAGATTCTAAGATGTCGTCGCAAGATGAATCTAAATTAGAAA...,ATGTCAGATTCTAAGATGTCGTCGCAAGATGAATCTAAATTAGAAA...,"[(0, 4506)]"
8,C5_01840C_A,"(24778, 28024)",TTAAATCCCCAAATTATTGTCAAAGAAAAAATTGGGTAAATTATTA...,TTAAATCCCCAAATTATTGTCAAAGAAAAAATTGGGTAAATTATTA...,"[(0, 2946)]"
9,C1_08460C_A,"(28024, 30463)",CTATTTCATATTCATAAACCCATTATCACCTTGCATTAAGTCTAAA...,CTATTTCATATTCATAAACCCATTATCACCTTGCATTAAGTCTAAA...,"[(0, 2139)]"
10,C3_04890W_A,"(30463, 35263)",ATGAGTACTGCAAACACGTCTTTGTCGCAACAGCTAGACGAAAAGC...,ATGAGTACTGCAAACACGTCTTTGTCGCAACAGCTAGACGAAAAGC...,"[(0, 4500)]"
11,C3_07860C_A,"(35263, 37696)",TTACGAGATTTTGAGGAAATCCCAATAATCCCAGTCCCAGTTTGAC...,TTACGAGATTTTGAGGAAATCCCAATAATCCCAGTCCCAGTTTGAC...,"[(0, 2133)]"
12,C6_03170C_A,"(37696, 39691)",CTAATTAGCATACTTAGATCTTGCTCTCAACTTTGGTCCGTTCAAG...,CTAATTAGCATACTTAGATCTTGCTCTCAACTTTGGTCCGTTCAAG...,"[(0, 1695)]"
13,C1_08590C_A,"(39691, 41482)",CTATCTTACAATCTCGTTCCATAAATATGGAGTAAAGATTACAATT...,CTATCTTACAATCTCGTTCCATAAATATGGAGTAAAGATTACAATT...,"[(0, 1491)]"
14,C3_02220W_A,"(41482, 43282)",ATGACAGATATTAAAAGAAATTTTTCAGATATTGCCTCACCAGCAA...,ATGACAGATATTAAAAGAAATTTTTCAGATATTGCCTCACCAGCAA...,"[(0, 1500)]"
15,C1_00800C_A,"(43282, 44236)",TTAGAATTTCCCAATTAATAAATTCTTGATCATATCTTTACCAGTG...,TTAGAATTTCCCAATTAATAAATTCTTGATCATATCTTTACCAGTG...,"[(0, 654)]"
16,C1_03780C_A,"(44236, 47758)",CTAAGATTTAATACATGTTACTGAACCTTCTTCAAGACGTTTCAAA...,CTAAGATTTAATACATGTTACTGAACCTTCTTCAAGACGTTTCAAA...,"[(0, 3222)]"
17,C3_06850W_A,"(47758, 49612)",ATGTCTGACGATCATTCAATCCATTCTCATACACAGGGACTCCACC...,ATGTCTGACGATCATTCAATCCATTCTCATACACAGGGACTCCACC...,"[(0, 1554)]"
18,CR_08780W_A,"(49612, 50051)",CTGATTTGCTTAATTGCACCACATGTGTTTTTCTTTGAAACAAACT...,CTGATTTGCTTAATTGCACCACATGTGTTTTTCTTTGAAACAAACT...,"[(0, 139)]"
19,CR_08800W_A,"(50051, 50502)",CTCCCTCAAACCGCTGGGTTTGGTGTTGAGCAATACGACTTGGGTT...,CTCCCTCAAACCGCTGGGTTTGGTGTTGAGCAATACGACTTGGGTT...,"[(0, 151)]"
20,C1_00710C_A,"(50502, 52531)",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]"
21,end,"(52531, 52531)",,,[]

In [14]:
def getExonSeq(Exon_coord, dna_seq):
    Exon_seqs_list = []
    for i in range(len(Exon_coord)):
        Exon_seqs_list.append(dna_seq[Exon_coord[0][0]:Exon_coord[0][1]])
    #print(Exon_seqs_list)
    s = ""
    return s.join(Exon_seqs_list)

#getExonSeq(df_albicans_genes.iloc[5]['exon coords'], df_albicans_genes.iloc[5]['dna seq'])

df_albicans_genes['exon seq'] = df_albicans_genes.apply(lambda row: getExonSeq(row['exon coords'], row['dna seq']), axis=1)

df_albicans_genes

,Gene ID,synth genome positions,match seq,dna seq,exon coords,exon seq
0,C5_00660C_A,"(0, 1887)",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
1,C1_04770C_A,"(1887, 3348)",TCATTGTTCAACATATTCTCTATCGTCAACTTTACCTTCAACTTCT...,TCATTGTTCAACATATTCTCTATCGTCAACTTTACCTTCAACTTCT...,"[(0, 1161)]",TCATTGTTCAACATATTCTCTATCGTCAACTTTACCTTCAACTTCT...
2,C1_02420C_A,"(3348, 9342)",TTAAACTCTGAATGGATTTGTAGAATAAGGGGTGGTAGTTCCAGTA...,TTAAACTCTGAATGGATTTGTAGAATAAGGGGTGGTAGTTCCAGTA...,"[(0, 5694)]",TTAAACTCTGAATGGATTTGTAGAATAAGGGGTGGTAGTTCCAGTA...
3,CR_00850C_A,"(9342, 14565)",CTAGTAATGCTTAATTTCTAATTTTTTCTTTAATCCTTTCAGATTT...,CTAGTAATGCTTAATTTCTAATTTTTTCTTTAATCCTTTCAGATTT...,"[(0, 4923)]",CTAGTAATGCTTAATTTCTAATTTTTTCTTTAATCCTTTCAGATTT...
4,C5_03390C_A,"(14565, 15522)",TTAAATACAGTAATATCTATCACCGAAATCACCTAGACCTGGAACA...,TTAAATACAGTAATATCTATCACCGAAATCACCTAGACCTGGAACA...,"[(0, 657)]",TTAAATACAGTAATATCTATCACCGAAATCACCTAGACCTGGAACA...
5,C6_00620W_A,"(15522, 16345)",ATGACGTTTGACGACAAAAAAGGTTTACAAGTTGCTCTTGATCAAG...,ATGACGTTTGACGACAAAAAAGGTTTACAAGTTGCTCTTGATCAAG...,"[(0, 55), (125, 523)]",ATGACGTTTGACGACAAAAAAGGTTTACAAGTTGCTCTTGATCAAG...
6,C3_05920W_A,"(16345, 19972)",ATGTCAATTGCCACCACCCCTATAGAAACACCTAAAAGTCCTAAAA...,ATGTCAATTGCCACCACCCCTATAGAAACACCTAAAAGTCCTAAAA...,"[(0, 3327)]",ATGTCAATTGCCACCACCCCTATAGAAACACCTAAAAGTCCTAAAA...
7,C3_05220W_A,"(19972, 24778)",ATGTCAGATTCTAAGATGTCGTCGCAAGATGAATCTAAATTAGAAA...,ATGTCAGATTCTAAGATGTCGTCGCAAGATGAATCTAAATTAGAAA...,"[(0, 4506)]",ATGTCAGATTCTAAGATGTCGTCGCAAGATGAATCTAAATTAGAAA...
8,C5_01840C_A,"(24778, 28024)",TTAAATCCCCAAATTATTGTCAAAGAAAAAATTGGGTAAATTATTA...,TTAAATCCCCAAATTATTGTCAAAGAAAAAATTGGGTAAATTATTA...,"[(0, 2946)]",TTAAATCCCCAAATTATTGTCAAAGAAAAAATTGGGTAAATTATTA...
9,C1_08460C_A,"(28024, 30463)",CTATTTCATATTCATAAACCCATTATCACCTTGCATTAAGTCTAAA...,CTATTTCATATTCATAAACCCATTATCACCTTGCATTAAGTCTAAA...,"[(0, 2139)]",CTATTTCATATTCATAAACCCATTATCACCTTGCATTAAGTCTAAA...
10,C3_04890W_A,"(30463, 35263)",ATGAGTACTGCAAACACGTCTTTGTCGCAACAGCTAGACGAAAAGC...,ATGAGTACTGCAAACACGTCTTTGTCGCAACAGCTAGACGAAAAGC...,"[(0, 4500)]",ATGAGTACTGCAAACACGTCTTTGTCGCAACAGCTAGACGAAAAGC...
11,C3_07860C_A,"(35263, 37696)",TTACGAGATTTTGAGGAAATCCCAATAATCCCAGTCCCAGTTTGAC...,TTACGAGATTTTGAGGAAATCCCAATAATCCCAGTCCCAGTTTGAC...,"[(0, 2133)]",TTACGAGATTTTGAGGAAATCCCAATAATCCCAGTCCCAGTTTGAC...
12,C6_03170C_A,"(37696, 39691)",CTAATTAGCATACTTAGATCTTGCTCTCAACTTTGGTCCGTTCAAG...,CTAATTAGCATACTTAGATCTTGCTCTCAACTTTGGTCCGTTCAAG...,"[(0, 1695)]",CTAATTAGCATACTTAGATCTTGCTCTCAACTTTGGTCCGTTCAAG...
13,C1_08590C_A,"(39691, 41482)",CTATCTTACAATCTCGTTCCATAAATATGGAGTAAAGATTACAATT...,CTATCTTACAATCTCGTTCCATAAATATGGAGTAAAGATTACAATT...,"[(0, 1491)]",CTATCTTACAATCTCGTTCCATAAATATGGAGTAAAGATTACAATT...
14,C3_02220W_A,"(41482, 43282)",ATGACAGATATTAAAAGAAATTTTTCAGATATTGCCTCACCAGCAA...,ATGACAGATATTAAAAGAAATTTTTCAGATATTGCCTCACCAGCAA...,"[(0, 1500)]",ATGACAGATATTAAAAGAAATTTTTCAGATATTGCCTCACCAGCAA...
15,C1_00800C_A,"(43282, 44236)",TTAGAATTTCCCAATTAATAAATTCTTGATCATATCTTTACCAGTG...,TTAGAATTTCCCAATTAATAAATTCTTGATCATATCTTTACCAGTG...,"[(0, 654)]",TTAGAATTTCCCAATTAATAAATTCTTGATCATATCTTTACCAGTG...
16,C1_03780C_A,"(44236, 47758)",CTAAGATTTAATACATGTTACTGAACCTTCTTCAAGACGTTTCAAA...,CTAAGATTTAATACATGTTACTGAACCTTCTTCAAGACGTTTCAAA...,"[(0, 3222)]",CTAAGATTTAATACATGTTACTGAACCTTCTTCAAGACGTTTCAAA...
17,C3_06850W_A,"(47758, 49612)",ATGTCTGACGATCATTCAATCCATTCTCATACACAGGGACTCCACC...,ATGTCTGACGATCATTCAATCCATTCTCATACACAGGGACTCCACC...,"[(0, 1554)]",ATGTCTGACGATCATTCAATCCATTCTCATACACAGGGACTCCACC...
18,CR_08780W_A,"(49612, 50051)",CTGATTTGCTTAATTGCACCACATGTGTTTTTCTTTGAAACAAACT...,CTGATTTGCTTAATTGCACCACATGTGTTTTTCTTTGAAACAAACT...,"[(0, 139)]",CTGATTTGCTTAATTGCACCACATGTGTTTTTCTTTGAAACAAACT...
19,CR_08800W_A,"(50051, 50502)",CTCCCTCAAACCGCTGGGTTTGGTGTTGAGCAATACGACTTGGGTT...,CTCCCTCAAACCGCTGGGTTTGGTGTTGAGCAATACGACTTGGGTT...,"[(0, 151)]",CTCCCTCAAACCGCTGGGTTTGGTGTTGAGCAATACGACTTGGGTT...
20,C1_00710C_A,"(50502, 52531)",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
21,end,"(52531, 52531)",,,[],

In [15]:
def getSynthLandmark(mutation_pos):
    for i in range(0,21):
        if ((int(mutation_pos) >= int(df_albicans_genes.iloc[i]['synth genome positions'][0])) & (int(mutation_pos) <= int(df_albicans_genes.iloc[i]['synth genome positions'][1]))):
            #print(df_albicans_genes.iloc[i]['synth genome positions'][0], df_albicans_genes.iloc[i]['synth genome positions'][1])
            return df_albicans_genes.iloc[i]['synth genome positions'][0]

In [16]:
df_merged['synth landmark'] = df_merged.apply(lambda row: getSynthLandmark(row['POS_test']), axis=1)

df_merged

,CHROM_test,POS_test,REF,ALT,AC_test,AF_test,AN_test,sample1.GT,sample2.GT,sample3.GT_test,CHROM_control,POS_control,AC_control,AF_control,AN_control,sample3.GT_control,synth landmark
0,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4031.0,2,0.500,4.0,./.,0
1,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4042.0,2,0.500,4.0,./.,0
2,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4044.0,2,0.500,4.0,./.,0
3,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,6656.0,2,0.500,4.0,./.,0
4,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,8174.0,2,0.500,4.0,./.,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87277,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,348856.0,2,0.333,6.0,T/T,50502
87278,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946773.0,2,0.333,6.0,T/T,50502
87279,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946782.0,2,0.333,6.0,T/T,50502
87280,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946812.0,2,0.333,6.0,T/T,50502
87281,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946943.0,2,0.333,6.0,T/T,50502

In [17]:
def getMutationPosition(pos, landmark):
    return (pos - landmark - 1) # base 0 strings

In [18]:
df_merged['Mutation pos in dna seq'] = df_merged.apply(lambda row: getMutationPosition(row['POS_test'], row['synth landmark']), axis=1)

df_merged

,CHROM_test,POS_test,REF,ALT,AC_test,AF_test,AN_test,sample1.GT,sample2.GT,sample3.GT_test,CHROM_control,POS_control,AC_control,AF_control,AN_control,sample3.GT_control,synth landmark,Mutation pos in dna seq
0,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4031.0,2,0.500,4.0,./.,0,117
1,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4042.0,2,0.500,4.0,./.,0,117
2,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4044.0,2,0.500,4.0,./.,0,117
3,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,6656.0,2,0.500,4.0,./.,0,117
4,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,8174.0,2,0.500,4.0,./.,0,117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87277,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,348856.0,2,0.333,6.0,T/T,50502,972
87278,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946773.0,2,0.333,6.0,T/T,50502,972
87279,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946782.0,2,0.333,6.0,T/T,50502,972
87280,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946812.0,2,0.333,6.0,T/T,50502,972
87281,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946943.0,2,0.333,6.0,T/T,50502,972

In [19]:
def getDNAseq(landmark):
    for i in range(0,21):
        if landmark == df_albicans_genes.iloc[i]['synth genome positions'][0]:
            return df_albicans_genes.iloc[i]['dna seq']

In [21]:
df_merged['dna seq'] = df_merged.apply(lambda row: getDNAseq(row['synth landmark']), axis=1)

df_merged

,CHROM_test,POS_test,REF,ALT,AC_test,AF_test,AN_test,sample1.GT,sample2.GT,sample3.GT_test,CHROM_control,POS_control,AC_control,AF_control,AN_control,sample3.GT_control,synth landmark,Mutation pos in dna seq,dna seq
0,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4031.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
1,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4042.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
2,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4044.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
3,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,6656.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
4,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,8174.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87277,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,348856.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87278,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946773.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87279,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946782.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87280,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946812.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87281,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946943.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...

In [22]:
def getExonseqForMergedDF(landmark):
    for i in range(0,21):
        if landmark == df_albicans_genes.iloc[i]['synth genome positions'][0]:
            return df_albicans_genes.iloc[i]['exon seq']

In [23]:
df_merged['exon seq'] = df_merged.apply(lambda row: getExonseqForMergedDF(row['synth landmark']), axis=1)

df_merged

,CHROM_test,POS_test,REF,ALT,AC_test,AF_test,AN_test,sample1.GT,sample2.GT,sample3.GT_test,CHROM_control,POS_control,AC_control,AF_control,AN_control,sample3.GT_control,synth landmark,Mutation pos in dna seq,dna seq,exon seq
0,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4031.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
1,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4042.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
2,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,4044.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
3,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,6656.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
4,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,Ca22chr1A_C_albicans_SC5314,8174.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87277,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,348856.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87278,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946773.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87279,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946782.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87280,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946812.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87281,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,Ca22chr5B_C_albicans_SC5314,946943.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...

In [24]:
def mutate_dna_sequence(dna_sequence, position, alt_aa):
    # Create a Biopython Seq object
    seq = Seq(dna_sequence)
    # Mutate the sequence at the specified position
    #mutated_seq = seq[:position-1] + alt_aa + seq[position:]
    mutated_seq = seq[:position] + alt_aa + seq[position:]
    return str(mutated_seq)

In [26]:
df_merged['mutated dna seq'] = df_merged.apply(lambda row: mutate_dna_sequence(row['dna seq'], row['Mutation pos in dna seq'], row['ALT']), axis=1)

df_merged

,CHROM_test,POS_test,REF,ALT,AC_test,AF_test,AN_test,sample1.GT,sample2.GT,sample3.GT_test,...,POS_control,AC_control,AF_control,AN_control,sample3.GT_control,synth landmark,Mutation pos in dna seq,dna seq,exon seq,mutated dna seq
0,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,4031.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
1,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,4042.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
2,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,4044.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
3,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,6656.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
4,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,8174.0,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87277,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,348856.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87278,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,946773.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87279,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,946782.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87280,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,946812.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87281,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,946943.0,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...

In [28]:
# Proof of mutation
print(df_merged.iloc[0]['dna seq'][117])

print(df_merged.iloc[0]['mutated dna seq'][117])

A
G

In [29]:
### Get mutated exon sequence

# Add exon coords to merged df...
def getExonCoordForMergedDF(landmark):
    for i in range(0,21):
        if landmark == df_albicans_genes.iloc[i]['synth genome positions'][0]:
            return df_albicans_genes.iloc[i]['exon coords']
        
df_merged['exon coords'] = df_merged.apply(lambda row: getExonCoordForMergedDF(row['synth landmark']), axis=1)

df_merged

,CHROM_test,POS_test,REF,ALT,AC_test,AF_test,AN_test,sample1.GT,sample2.GT,sample3.GT_test,...,AC_control,AF_control,AN_control,sample3.GT_control,synth landmark,Mutation pos in dna seq,dna seq,exon seq,mutated dna seq,exon coords
0,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]"
1,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]"
2,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]"
3,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]"
4,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,2,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87277,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]"
87278,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]"
87279,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]"
87280,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]"
87281,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,2,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]"

In [30]:
# Get mutated exon seq

#df_merged['mutated exon seq'] = df_merged.apply(lambda row: getExonseqForMergedDF(row['dna seq'], row['Mutation pos in dna seq'], row['ALT']), axis=1)
#df_merged

df_merged['mutated exon seq'] = df_merged.apply(lambda row: getExonSeq(row['exon coords'], row['mutated dna seq']), axis=1)

df_merged

,CHROM_test,POS_test,REF,ALT,AC_test,AF_test,AN_test,sample1.GT,sample2.GT,sample3.GT_test,...,AF_control,AN_control,sample3.GT_control,synth landmark,Mutation pos in dna seq,dna seq,exon seq,mutated dna seq,exon coords,mutated exon seq
0,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
1,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
2,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
3,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
4,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,0.500,4.0,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87277,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87278,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87279,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87280,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...
87281,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,0.333,6.0,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...

In [31]:
def translate(exon_sequence):
    # Create a Biopython Seq object
    seq = Seq(exon_sequence)
    # Translate the sequence using the specified genetic code
    aa_sequence = seq.translate(table=12)
    return str(aa_sequence)

In [32]:
df_merged['AA seq'] = df_merged.apply(lambda row: translate(row['exon seq']), axis=1)
df_merged['mutated AA seq'] = df_merged.apply(lambda row: translate(row['mutated exon seq']), axis=1)
df_merged

/home/labolandry/anaconda3/lib/python3.10/site-packages/Bio/Seq.py:2879: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(
/home/labolandry/anaconda3/lib/python3.10/site-packages/Bio/Seq.py:2879: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(

,CHROM_test,POS_test,REF,ALT,AC_test,AF_test,AN_test,sample1.GT,sample2.GT,sample3.GT_test,...,sample3.GT_control,synth landmark,Mutation pos in dna seq,dna seq,exon seq,mutated dna seq,exon coords,mutated exon seq,AA seq,mutated AA seq
0,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*IINKSS*...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*DYKQK*L...
1,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*IINKSS*...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*DYKQK*L...
2,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*IINKSS*...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*DYKQK*L...
3,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*IINKSS*...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*DYKQK*L...
4,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,./.,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*IINKSS*...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*DYKQK*L...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87277,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...
87278,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...
87279,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...
87280,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...
87281,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,T/T,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...

In [33]:
# testing
#list(df_merged.iloc[0]['AA seq'])[0]

'L'

In [34]:
def getDeltaAA(WT, MUT):
    for i, aa in enumerate(list(MUT)):
        if aa != list(WT)[i]:
            return (i, aa)
    
    return 0

In [35]:
df_merged['delta AA'] = df_merged.apply(lambda row: getDeltaAA(row['AA seq'], row['mutated AA seq']), axis=1)

df_merged

,CHROM_test,POS_test,REF,ALT,AC_test,AF_test,AN_test,sample1.GT,sample2.GT,sample3.GT_test,...,synth landmark,Mutation pos in dna seq,dna seq,exon seq,mutated dna seq,exon coords,mutated exon seq,AA seq,mutated AA seq,delta AA
0,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*IINKSS*...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*DYKQK*L...,"(39, D)"
1,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*IINKSS*...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*DYKQK*L...,"(39, D)"
2,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*IINKSS*...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*DYKQK*L...,"(39, D)"
3,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*IINKSS*...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*DYKQK*L...,"(39, D)"
4,Candidaalbicans,118,A,G,2,0.500,4,A/G,A/G,./.,...,0,117,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,"[(0, 1587)]",TTAAAACATACAAGTTTCTCTTTTTTCCCAAATGATTTCTGCTGGT...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*IINKSS*...,LKHTSFSFFPNDFCWFSR*NHH*TIIRVRHFITINSPS*DYKQK*L...,"(39, D)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87277,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,"(324, C)"
87278,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,"(324, C)"
87279,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,"(324, C)"
87280,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,"(324, C)"
87281,Candidaalbicans,51475,G,T,2,0.333,6,G/G,G/G,T/T,...,50502,972,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,"[(0, 1302), (1466, 1502), (1717, 1729)]",TTATTCCATGGCGGCATCTTCTAATGGGATTTCATCGGCATATTCT...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,LFHGGIF*WDFIGIF*FFFINTSFLVLLVFTNQIIHIRFSFSKFHF...,"(324, C)"

In [36]:
# df_merged.to_csv("vcf_analysis.csv") the csv is 1.2 gigabytes...